[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200